# Uncomment the next line to define a global platform for your project
# platform :ios, '17.2'

target 'Doughnut' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'NMapsMap'
  pod 'SnapKit'
  pod 'KakaoSDK'
  pod 'KakaoSDKCertCore'
  pod 'SnapKit-Dynamic'
  pod 'KakaoSDKAuth'
  pod 'KakaoSDKCommon'
  pod 'KakaoSDKCert'

  # Pods for Doughnut

  target 'DoughnutTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DoughnutUITests' do
    # Pods for testing
  end

end
