# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

target 'DonutApp' do
    pod 'SnapKit', '~> 5.0'
end
